Repository TexasCodeEm/cse112-sp22-team6, pull requests merged in 2022-06, with the labels that each got.

#56 Typos for UI fix
  README.md
  source/scripts/settings.js
  source/scripts/util/language.js
  source/tests/language-pomodoro.test.js
  source/tests/manual-testing.md
  source/tutorial-scripts/tutorial_page.js
  source/tutorial_page.html
Labels: documentation, testing, devops

#58 Added Crypress tests
  cypress/integration/main/backgrounds.spec.js
  cypress/integration/main/combination.spec.js
  cypress/integration/main/languages.specs.js
  cypress/integration/main/tutorial.spec.js
  source/tutorial-scripts/language_tutorial.js
  source/tutorial_page.html
Labels: testing, devops

#63 Adding ADRs
  docs/adr/disable-buttons.md
  docs/adr/settings-button-design.md
Labels: documentation

#64 Added sprint 4 docs and wireframes
  docs/load times/Screen Shot 2022-05-21 at 4.41.12 AM.png
  docs/load times/Screen Shot 2022-05-21 at 6.40.46 PM.png
  docs/load times/Screen Shot 2022-05-22 at 4.04.52 PM.png
  docs/load times/Screen Shot 2022-05-23 at 6.59.40 PM.png
  docs/load times/Screen Shot 2022-05-23 at 7.09.20 PM.png
  docs/load times/Screen Shot 2022-05-23 at 7.57.42 PM.png
  docs/load times/Screen Shot 2022-05-24 at 1.59.28 AM.png
  docs/load times/Screen Shot 2022-05-24 at 11.20.39 AM.png
  docs/load times/Screen Shot 2022-05-29 at 1.00.32 AM.png
  docs/load times/Screen Shot 2022-06-07 at 7.22.19 PM.png
  docs/sprint plans/sprint4.md
  docs/wireframes/UserFlowWireframe.png
  docs/wireframes/mobileWireframes.png
Labels: documentation

#65 tutorial button fix when timer resets
  source/scripts/timer.js
Labels: design
